version: '3.8'


services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postuser
      POSTGRES_PASSWORD: db.password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data: /var/lib/postgresql/data
    

  py:
    build: ./app
    ports: 
      - "5000:5000"
    environments:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postuser
      DB_PASSWORD: db.password
    depends_on:
      - db

volumes:
   db_data:
     driver: local
